# Generated by Django 4.2.7 on 2023-12-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='varb',
            new_name='verb',
        ),
    ]
